services:
  strapi-db:
    container_name: strapi-db.cloud-sql-proxy
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.5.0
    command: ${CLOUD_SQL_CONNECTION_NAME} --json-credentials '${CLOUD_SQL_SERVICE_ACCOUNT_JSON}' --address 0.0.0.0 --port 5432
    networks:
      - strapi
    ports:
      - 5432:5432